Update scripts.

diff --git a/generate_manual b/generate_manual
--- a/generate_manual
+++ b/generate_manual
@@ -5,15 +5,35 @@
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 DATE="$(date "+%B %e, %Y")"
 
-MANUAL_NAME="manual_example"
+MANUAL_NAME=$1
 MANUAL_IN_DIR=$DIR/$MANUAL_NAME
-MANUAL_OUT_DIR=$DIR/output/$MANUAL_NAME
+MANUAL_OUT_DIR=$DIR/export/$MANUAL_NAME
 
 ###################################################################################################
 
 error=0
 
 echo ""
+
+# Check if name of manual to be generated has been provided
+if [ $# -lt 1 ]; then
+    echo "You need to provide the manual name to be generated."
+    echo "  Example:"
+    echo "    ./generate_manual manual_example"
+    echo ""
+    exit 1
+fi
+
+# Check if Pandoc is installed
+pandoc -v &> /dev/null
+if [[ $? != 0 ]]; then
+    echo "Error: Pandoc not found."
+    echo "Please install it through \"pandoc_install\" script."
+    echo ""
+    exit 1
+fi
+
+# Create output directory
 mkdir -p $MANUAL_OUT_DIR
 
 # Generate HTML, ODT and PDF documents from Markdown plain text files
@@ -32,15 +52,23 @@ if [[ $? != 0 ]]; then
     echo ""
 fi
 echo "Creating PDF manual..."
-pandoc -H "${MANUAL_IN_DIR}/tex_to_pdf_style.tex" --top-level-division=chapter -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o $MANUAL_OUT_DIR/$MANUAL_NAME.pdf
+#pandoc -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o $MANUAL_OUT_DIR/$MANUAL_NAME.pdf
+#if [[ $? != 0 ]]; then
+#    ((error=error+1))
+#    echo "Error: Can't generate manual in PDF format."
+#    echo ""
+#fi
+#echo "Creating PDF book..."
+#pandoc -H "${MANUAL_IN_DIR}/tex_to_pdf_style.tex" --top-level-division=chapter -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o "${MANUAL_OUT_DIR}/${MANUAL_NAME}_book.pdf"
+pandoc -H "${MANUAL_IN_DIR}/tex_to_pdf_style.tex" --top-level-division=chapter --columns=100 -M date="${DATE}" $MANUAL_IN_DIR/*.md -f markdown -s -o "${MANUAL_OUT_DIR}/${MANUAL_NAME}.pdf"
 if [[ $? != 0 ]]; then
     ((error=error+1))
-    echo "Error: Can't generate manual in PDF format."
+    echo "Error: Can't generate book in PDF format."
     echo ""
 fi
 
 echo ""
-if [ $error -eq 3 ]; then
+if [ $error -ge 3 ]; then
     echo "Error: Manual can't be created."
     rm -rf $MANUAL_OUT_DIR
 else
