Allow show install script help info without root privileges.

diff --git a/pandoc_install b/pandoc_install
--- a/pandoc_install
+++ b/pandoc_install
@@ -9,15 +9,6 @@ PANDOC_DEB_PKG="https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.
 help=0
 force=0
 
-###################################################################################################
-
-# Check for root privileges
-if [ "$(id -u)" != "0" ]; then
-    echo "This script must be executed with administration privileges."
-    echo ""
-    exit 1
-fi
-
 ###############################################################################
 
 # For each argument
@@ -49,6 +40,15 @@ if [ $help -eq 1 ]; then
     printf "system repositories.\n"
     printf "\n"
     exit 0
+fi
+
+###################################################################################################
+
+# Check for root privileges
+if [ "$(id -u)" != "0" ]; then
+    echo "This script must be executed with administration privileges."
+    echo ""
+    exit 1
 fi
 
 ###################################################################################################
@@ -128,6 +128,15 @@ else
     rm -f ./pandoc*.deb
 fi
 echo ""
+
+# Check if Pandoc was successfully installed
+pandoc -v &> /dev/null
+if [[ $? != 0 ]]; then
+    echo "Error: Pandoc not found."
+    echo "Seems that something goes wrong."
+    echo ""
+    exit 1
+fi
 
 echo "Markdown-Pandoc Workbench Requeriments successfully installed."
 echo ""
